src/components/admin/AdminBookingList.tsx, src/components/bookings/timeEstimate/TimeEstimateList.tsx, src/components/bookings/timeReport/TimeReportList.tsx, src/components/layout/Topbar.tsx, src/components/utils/TimeReportHourDisplay.tsx, src/lib/datetimeUtils.ts, src/lib/db-access/booking.ts, src/lib/db-access/index.ts, src/lib/pricingUtils.ts, src/pages/api/users/[id]/timeReportBookings.ts, src/pages/users/[id]/index.tsx, src/pages/users/[id]/time-reports.tsx
En sida där man kan se sina tidsrapporter och hur mycket man kommer få i lön, som diskuterat igår. Passade även på att justera några “tidsrapporter“ till “tidrapporter“ när jag ändå var igång.
---
Några designbeslut alla jag tagit som är bra att veta om:
- Bokningarna är grupperade på bokningens startdatum. Detta är konsekvent med hur vi gör överallt annars, men jag vet inte hur ekonomichef brukar hantera det vid löneutbetalning. Om en bokning startar 31a och slutar 3e, vilken månad får man lön i? Oavsett hur de fallen hanteras kan det ju även vara cornercases där evenemang pågår över flera månader (som vårt allas favoritspecialfall: international reception), och då kommer de ju hamna i fel månad oavsett - men att det sker ibland tycker jag är ok. Vi kommer ju aldrig vara 100% korrekta …
=> Feature: Add time-report page

src/lib/pricingUtils.ts
Currency.js broke the formatter (i.e. which of hour/units) are shown
=> Bugfix: Fix price format

src/pages/api/customers/index.ts, src/pages/api/equipmentLocations/index.ts, src/pages/api/equipmentPublicCategories/index.ts, src/pages/api/equipmentTags/index.ts, src/pages/settings.tsx
Now non-admins can't access the page and get only GET data from the APIs.
Previously they could view and add entities, but not edit or delete them.
=> Bugfix: Fix inconsistent non-admin access to settings

src/document-templates/components/shared/equipmentListInfo.tsx
Detta är absolut inte en optimal lösning, men en snabb workaround/quickfix på formatteringsproblemet med långa beskrivningar i dokumentexporterna.
Jag har helt enkelt lagt beskrivningen på en egen rad, så kan den bli så bred den vill utan att den överlappar någon annan text.
Långa titlar kommer dock fortfarande vara problematiska såklart, men det är ju ovanligare.
=> Bugfix: Document formatting quickfix

README.md, src/lib/authenticate.ts, src/lib/db-access/user.ts, src/lib/sessionContext.ts, src/pages/api/external/v1/usersByNameTag/[nameTag].ts
Add support for public/external APIs. Also includes an example endpoint which fetches user information based on name tags.
Authentication is done with tokens using the `X-API-KEY` header. Serverside the list of accepted tokens are configured as an env. variable called `API_KEYS` using a JSON list.
---
To test the provided example endpoint you need to configure backstage2 to accept a key by configuring the env variable, for example:
```
API_KEYS=[{"key": "15ec21b2-6f93-11ee-b962-0242ac120002", "name": "test"}]
```
You can then call the API with:
```
curl --location 'localhost:3000/api/external/v1/usersByNameTag/AM' \
--header 'X-API-KEY: 15ec21b2-6f93-11ee-b962-0242ac120002'
```
Example:
---
Related trello card: https://trello.com/c/yG0qDyLC/417-bygg-publikt-api
=> Feature: Add public API support

src/lib/changelogUtils.ts, src/lib/slack.ts
DM is send when:
* Rental status is changed
* Booking status is changed
Vi pratade ~~i tisdags~~ _i oktober_ om att det vore nice att få lite mer påminnelse den som är ansvarig för en hyra att kolla över efter den är tillbakalämnad. Ett sätt att göra det är ju att man får en pling så man slipper komma ihåg att hålla koll på vad som händer själv.
Med denna PR skickas ett DM i slack till ägaren för en bokning när utlämningsstatus eller bokningsstatus ändras om ägaren har ett slack-id konfigurerat och det inte var ägaren själv som utförde statusändringen. Se exempel i bild nedan:
Nu är det som sagt bara utlämningsstatus och bokningsstatus som det uppdateras om, men vi kan ju lägga till fler saker (betalstatus, lönestatus, tidsrapporter, skapande av bokningar, etc) om vi tycker det är …
=> Feature: Send slack DM to owner of a booking on update

src/components/equipment/EquipmentBookings.tsx
The "top 10" filter on past bookings did not work correctly since the list isn't sorted. Since it might be interesting to see more than 10 bookings (and we load them from the server regardless) I just show all of them.
Trello card: https://trello.com/c/T1Gkqxbz/415-senaste-10-bokningarna-som-anv%C3%A4nt-utrustning-verkar-inte-uppdatera-efter-%C3%A5rsskiftet-se-tex-tri-led
=> Bugfix: Show all past bookings on equipment

src/components/admin/AdminBookingList.tsx, src/components/bookings/equipmentLists/EquipmentListHeader.tsx, src/components/bookings/equipmentLists/EquipmentListTable.tsx, src/components/bookings/timeEstimate/TimeEstimateList.tsx, src/components/bookings/timeReport/TimeReportList.tsx, src/components/utils/DoubleClickToEdit.tsx
* Rename DoubleClickToEdit component to ClickToEdit
* Fix tracking error when value is changed elsewhere after component is rendered
Trello card: https://trello.com/c/lkgc5edt/386-om-man-byter-namn-p%C3%A5-en-tidsrapport-via-avancerad-redigering-och-sedan-f%C3%B6rs%C3%B6ker-byta-namn-genom-att-klicka-p%C3%A5-namnet-och-avbryte
=> Bugfix: Rename DoubleClickToEdit component and fix value tracking

src/components/bookings/equipmentLists/CopyEquipmentListEntriesModal.tsx, src/components/bookings/equipmentLists/EditEquipmentListEntryModal.tsx, src/lib/mappers/booking.ts, src/models/interfaces/EquipmentList.ts, src/models/objection-models/BookingObjectionModel.ts
Fix saving removal of equipment connection on equipment list entry.
Previously the connection removal wasn't saved server-side and the connection came back on the next data reload. This is fixed by sending `null` as the equipment id and related properties instead of `undefined` which is striped in the JSON conversion.
=> Bugfix: Fix remove connected equipment

src/lib/db-access/booking.ts, src/pages/api/external/v1/analytics/bookings.ts
Add an endpoint to fetch basic analytics in csv format for analysis elsewhere. It uses the public API support introduced in PR #25, i.e. you need an API key to access the endpoint.
This PR provides a minimal set of information on a booking level to enable a proof-of-concept analytics page. For each booking the following data is provided:
* Basic information such as name, type, responsible user, created date location, and language
* All booking-level statuses (booking, payment, salary)
* Customer information (name and hogia id)
* Pricing metadata (price plan and account kind)
* Pricing (equipment total, time estimate total and time report total)
* Dates (usage start/end and equipment in/out)
* Working hours information (estimated, actual and billable)
See example response below:
The …
=> Feature: Add analytics API

src/components/CurrentlyOutEquipment.tsx, src/lib/db-access/equipmentList.ts, src/models/misc/CurrentlyOutEquipmentInfo.ts, src/pages/api/equipment/currentlyOut.ts, src/pages/index.tsx
Show a list of currently out equipment on first page. To be more specific, two things are shown:
* Equipment which belongs to an equipment list on a rental booking with status out - i.e. equipment which is on a rental.
* Equipment which belongs to an equipment list on a gig booking which takes place now (either usage dates or equipment out dates)
=> Feature: Show currently out equipment on front page

src/components/ChangelogCard.tsx, src/components/bookings/BookingSearchCustomerModal.tsx, src/components/bookings/BookingStatusButton.tsx, src/components/bookings/equipmentLists/CopyEquipmentListEntriesModal.tsx, src/components/bookings/equipmentLists/EditEquipmentListDatesModal.tsx, src/components/bookings/equipmentLists/EditEquipmentListEntryModal.tsx, src/components/bookings/equipmentLists/EquipmentListTable.tsx, src/components/bookings/equipmentLists/PackageInfoModal.tsx, src/components/bookings/equipmentLists/SelectNumberOfUnitsAndHoursModal.tsx, src/components/bookings/timeEstimate/TimeEstimateAddButton.tsx, src/components/bookings/timeEstimate/TimeEstimateModal.tsx, src/components/bookings/timeReport/TimeReportAddButton.tsx, src/components/bookings/timeReport/TimeReportModal.tsx, src/components/invoices/CreateInvoiceGroupModal.tsx, src/components/layout/LoggedOutModal.tsx, src/components/layout/Topbar.tsx, src/components/salaries/CreateSalaryGroupModal.tsx, src/components/settings/BaseEntityWithNamesEditor.tsx, src/components/statistics/AccountStatistics.tsx, src/components/utils/ConfirmModal.tsx, src/components/utils/EditTextModal.tsx, src/components/utils/setting/SettingsModal.tsx, src/pages/users/[id]/edit.tsx
Adjust modal behavior so a click outside the modal does not close it. Note: `Esc` still closes the modal.
I have checked our modals and alla modals have either a Cancel-button (about 90%) or an X-button to close the in the top corner.
---
Resolves #50
=> Feature: Adjust modals so they dont close on click outside

src/document-templates/components/priceEstimateDocument.tsx, src/document-templates/components/rentalConfirmationDocument.tsx, src/document-templates/defaultTextResources.ts
Price estimate and rental agreement now links to the terms and conditions page on our website.
=> Feature: Add rental terms link to documents

src/components/bookings/PreviousBookingsCard.tsx, src/pages/bookings/[id]/index.tsx
Add a list on the booking page showing the customers previous bookings. This is done by matching on Hogia Id. 
If the booking does not have a Hogia Id a message is shown that this feature only works for customers with Hogia Ids.
For now, this list works the same way as the lists on the front page - i.e. all bookings are fetched and the filtering is done client side.
Note: I opted to not show booking statuses, type, etc here since it made the UX very cluttered, but maybe it's worth the clutter to get that information and to be consistent?
---
=> Feature: Show customers other bookings on booking page

src/components/admin/SendMessageToBookingOwnersButton.tsx, src/components/bookings/timeEstimate/TimeEstimateAddButton.tsx, src/components/bookings/timeReport/TimeReportAddButton.tsx, src/lib/slack.ts, src/pages/admin-overview.tsx, src/pages/api/sendMessage/toBookingOwners.ts
Allow admins to send slack messages to owners of bookings. The primary use case for this is to remind people to update the statuses for their bookings without having to manually generate a list of users to message and manually contacting them.
---
---
Resolves #54
=> Feature: Admin slack messages

src/components/bookings/equipmentLists/EditEquipmentListDatesModal.tsx
This is a bit of an experiment which I am still not sure if I like, but I would like some input from others.
We have a few bookings each year where each equipment list actually represent different events, primarily during the receptions but also for spexes with multiple rehearsals etc. If you have a lot of equipment lists it can be quite a hassle to input the wildly different times for each equipment list manually, which often is made extra frustrating since that data is already available in the calendar but cannot be imported in any way.
We have already decided that we do not want to change the primary connection between a booking in stage and an calendar event, but I wanted to test a looser connection in the form of a one-off fetch-from-calendar-action, similar to the calendar …
=> Feature: Add wizard to fetch list times from calendar

src/components/bookings/timeReport/TimeReportList.tsx
Show a warning when there are overlapping time reports for the same user. The warning has the same UX as the overlapping equipment usage warning.
---
=> Feature: Show warning on overlapping time reports

src/components/bookings/timeEstimate/TimeEstimateList.tsx, src/components/bookings/timeReport/TimeReportModal.tsx
Fix unintended reorder of time reports and estimates to end of list when using advanced edit.
=> Bugfix: Fix unintended reorder of time reports and estimates on advanced edit

src/components/admin/SendMessageToBookingOwnersButton.tsx
Improve performance of "send message to booking owners" by not only rendering each tab once.
The problem was the message update triggering a re-render of the component. This included the first tab, which attempted to format all dates of all past bookings (which is performance-intensive). Previously this list existed in the DOM, but where hidden by CSS - with this update it is not rendered at all, which greatly reduces the computational need. Additionally, the component now used the dates rendered by the parent.
Tested on 1000 booking locally, which worked fine (it turns out it is quite easy to get large testing sets by adding loops in mock.js).
---
Resolves #81
=> Bugfix: Improve send message to booking owners performance

src/lib/utils.ts, src/pages/index.tsx
Home screen now shows upcoming rentals for 1 week ahead instead of 24h. Closes #82.
=> Extend time span for upcoming rentals list

knex/seeds/mock.js
Set actual fixed price account in mock.js instead of placeholder XXXX to align with other account settings.
=> Feature: Set actual fixed price account in mock.js

src/components/admin/AdminBookingList.tsx
This works now (as of #56) so no warning is needed.
---
Resolves #94
=> Feature: Remove warning for both fixed price and time reports

knex/migrations/20250131000000_package_equipment_price.js, src/components/equipmentPackage/EquipmentPackageForm.tsx, src/components/equipmentPackage/PackageEquipmentList.tsx, src/lib/db-access/equipmentPackage.ts, src/lib/equipmentListUtils.ts, src/lib/mappers/equipmentPackage.ts, src/models/interfaces/EquipmentPackage.ts, src/models/objection-models/EquipmentPackageObjectionModel.ts
Add a field for selecting price for each equipment in packages. This allows you to create packages such as "Stagepodiums for use outside", "GrandMA3 Command Wing with Computer", or similar and having the equipment select the appropriate price when used.
To allow for backwards compatability you may also choose no price, which results in the standard default price behavior. If the selected price is deleted, the equipment package entry defaults back to this behavior (aka the property is nullable).
---
Resolves #92
=> Feature: Select price on equipment packages

src/lib/slack.ts, src/pages/api/sendMessage/toBookingOwners.ts
Start groups (with the bot, the sender, and the booking owner) instead of only a message between the bot and the owner when sending admin messages from stage. This allows the booking owner to respond to the sender in the same channel, and allows the sender to see what has been sent.
Please note: This requires the [mpim:write](https://api.slack.com/scopes/mpim:write) slack permission in addition to chat:write
---
Resolves #88
=> Feature: Start DM groups when messaging booking owners

knex/migrations/20250125000000_equipment-list-entry-is-packed.js, src/components/bookings/equipmentLists/CopyEquipmentListEntriesModal.tsx, src/components/bookings/equipmentLists/EditEquipmentListEntryModal.tsx, src/components/bookings/equipmentLists/EquipmentListHeader.tsx, src/lib/equipmentListUtils.ts, src/models/interfaces/EquipmentList.ts, src/models/objection-models/BookingObjectionModel.ts, src/pages/api/bookings/[bookingId]/equipmentListEntry/[equipmentListEntryId].ts, src/pages/bookings/[id]/equipmentList/[listId]/index.tsx
This is a simple implementation of a web-based packing list using the available component/techniques. It uses swr with polling every 10 seconds (while the page is in focus) to keep the information somewhat "live" while multiple people are packing at the same time. It would of course be even better with a websockets-based implementation, but that will take much more effort so I think this is a good start.
The packing-list feature is accessed from the "Mer"-dropdown in the booking view, but it also allows users to switch between multiple lists on the same booking without leaving the packlist interface. These packing list buttons are only available for bookings which are not marked as done, and only users with write-access to stage are allowed to update it. Updates to the packing status of …
=> Feature: Packlist in web interface (using swr/polling)

src/components/bookings/BookingStatusButton.tsx, src/components/bookings/equipmentLists/EquipmentListHeader.tsx
Improve UX to encourage users to set dates for equipment in and out.
* New warning when setting rentals to booked if any list is missing configured dates.
* Booked rentals now have the default dates (i.e. usage start and usage end) in red instead of gray if configured equipment in and out dates are missing.
---
Resolves #79
=> Feature: UX to encourage users to set equipment dates

src/components/layout/Search.tsx
set href on the Typehead MenuItem used for the search result which lets the browswer knows that it links to a url which can be used to open in a new tab.
=> Feature: open searchresult in new tab

knex/seeds/mock.js, src/components/AddUserAsCoOwnerToAllFutureBookingsForUserButton.tsx, src/components/LargeBookingTable.tsx, src/components/ManageCoOwnerBookingsButton.tsx, src/components/TinyBookingTable.tsx, src/components/bookings/CalendarWorkersCard.tsx, src/components/bookings/FilesCard.tsx, src/lib/calenderUtils.ts, src/lib/db-access/user.ts, src/lib/db-access/utils.ts, src/lib/slack.ts, src/models/misc/CalendarResult.ts, src/pages/api/bookings/[bookingId]/equipmentListEntry/[equipmentListEntryId].ts, src/pages/api/calendar/[id].ts, src/pages/api/calendar/index.ts, src/pages/api/calendar/open-hours.ts, src/pages/api/sendMessage/toBookingWorkers.ts, src/pages/bookings/[id]/index.tsx, src/pages/index.tsx
At the meeting yesterday we discussed fetching the users working bookings from the calendar, by parsing the prefix of the calendar event name. This is a POC of that, which includes three features:
* Save all bookings I will work at as favorites (aka _coOwnerBookings_)
* Show which users are signed up in the calendar for an event connected to booking
* Create a slack channel or start DM-group for a booking
All of these are built on top of a new field in the calendar event endpoint: WorkingUsers. This field is populated by identifying the user name tags in the brackets at the start of the calendar event name (using regex, comma separation, and substrings to try to remove noise). These tags are then matched with the stage user database to find any matches.
**Save all booking I will work at …
=> Feature: Fetch working users of bookings from calendar

src/components/bookings/equipmentLists/EquipmentListHeader.tsx
Add tooltips which explain why the dates are red on the equipment list. 
Also only show the warning for Rentals (not Gigs).
=> Feature: Add tooltips for missing dates in EquipmentListHeader

src/components/bookings/CalendarWorkersCard.tsx, src/pages/bookings/[id]/index.tsx
Add button to connect a calendar event, if it does not already exist. If a connection exists, the same menu can be accessed from the Mer-dropdown which enabled the user to change the connected calendar event. The UI to select is the same as is used for the bemanning-wizard-feature.
Since we only fetch future events from the calendar API, we show a warning message if the user tries to edit a connection for which we cannot find the current value in the list of future calendar events.
Booking without calendar connection:
Booking with existing calendar connection:
Edit modal:
Warning message described above:
=> Feature: Calendar event selection on existing booking

src/components/bookings/equipmentLists/CopyEquipmentListEntriesModal.tsx, src/components/bookings/equipmentLists/EditEquipmentListEntryModal.tsx, src/components/bookings/equipmentLists/EquipmentListTable.tsx, src/components/bookings/equipmentLists/SelectNumberOfUnitsAndHoursModal.tsx, src/lib/equipmentListUtils.ts, src/pages/public/prices.tsx
Handle equipment with no prices in price selection logic to avoid crash.
Most of this PR is just type changes to reflect the new logic - the actual fix is these lines:
```
if (prices.length === 0) {
return null;
}
```
Additionally, I also adjusted `CopyEquipmentListEntriesModal `to use the price selection function from `equipmentListUtils`.
=> Bugfix: Handle equipment with no prices in price selection logic

src/lib/calenderUtils.ts
If the calendar name tag list looks like `'[AA, BB/CC, DD]'` we now split on the `'/'` try to find users `BB` and `CC` instead of a user `BB/CC`.
=> Feature: Handle '/' in calendar name-tag list

src/lib/db-access/booking.ts, src/pages/api/bookings/active.ts, src/pages/bookings/index.tsx, src/pages/index.tsx
Previously all bookings (regardless of status, time, or other criteria) where always fetched for the front page and all lists of bookings. This made the front-page lists of upcoming rentals, out rentals, etc needlessly slow. By limiting these booking-list requests to only drafts and booked bookings (aka not done or cancelled) we can drastically reduce the payload size and the database read.
In my testing (with a copy of the production database from july) this reduces the load time from about 500ms to about a 100ms, so it loads (and feels) much faster. The number of bookings is reduced from about 800 to about 60, which further improves rendering speed etc.
In practice, this should have no impact on the results show (in theory there is a rare cases where done or cancelled bookings have …
=> Feature: Improve performance by only fetching active bookings

src/components/BookingSearch.tsx
Align which fields are displayed when using the BookingSearch component (for example copy equipment from other booking modal) so it is same as the search in the top bar.
Most importantly, the date is now shown so you can differentiate bookings repeating each year.
=> Feature: Align booking search result component with top-bar search
