rneventteknik/backstage2

src/pages/bookings/[id]/index.tsx
=> Feature: Rename price headings

src/components/bookings/BookingStatusButton.tsx, src/pages/bookings/[id]/edit.tsx, src/pages/bookings/[id]/index.tsx
- Move delete from edit page to index in a 'Mer'-dropdown
- Move cancel from status button to the same 'Mer'-dropdown
- Show why a booking cannot be booked (i.e. dates are missing)
- Move price estimate export button into dropdown
- Add invoice exports for admins
=> Feature: Booking page UX improvements

src/components/layout/Search.tsx, src/lib/db-access/booking.ts
Diskuterar gärna exakt datumformat som är lämpligt, nu tog jag ett vi hade för enkelhetens skull så kan vi byta om vi vill.
=> Feature: Equipment date in search

src/components/bookings/equipmentLists/EquipmentListTable.tsx, src/components/equipment/EquipmentForm.tsx, src/document-templates/utils.ts, src/lib/pricingUtils.ts
They both set the entry price to 0 using discount and custom price respectively.
=> Feature: Add two options for setting price to 0 in "mer" menu

src/components/salaries/CreateSalaryGroupModal.tsx
Trello card: https://trello.com/c/4xiucToP/427-b%C3%A5de-l%C3%B6neunderlagsrupp-och-timarvodesunderlagsgrupp-anv%C3%A4nds-p%C3%A5-sidan-f%C3%B6r-timarvodesunderlagsexport
=> Bugfix: Fix salary terms

src/components/bookings/equipmentLists/SelectNumberOfUnitsAndHoursModal.tsx
Trello card: https://trello.com/c/JK9MSe2V/414-krasch-om-man-l%C3%A4gger-till-utrustning-utan-pris
=> Bugfix: Fix crash when adding equipment with no price

src/components/admin/AdminBookingList.tsx, src/components/utils/CancelledIcon.tsx
Trello card: https://trello.com/c/oQ5yRRK9/412-f%C3%A4rgkoda-inst%C3%A4lld-i-admin%C3%B6versikten
=> Feature: Color code cancelled bookings in admin overview

src/pages/statistics.tsx
_This tweak to the statistics is based on a discussion I had with Teo during the stormöte fika break, where we talked about which statistic enhancements would make the economy responsible job easier._
----
Add a small filter section to the statistics page. It has two filters with two different purposes:
* A multi-select to select which statuses are included. This can be used to show for example booked and draft bookings, in order to project future earnings (requested by Teo). Previously only Done bookings were included.
* A checkbox to include or not include bookings with fixed price 0. This can be used to remove internal bookings (i.e. borrowed equipment, bookings which actually represent repairs, and other internal events) from the statistics, potentially making the statistics more …
=> Feature: Add booking filters to statistics page

src/components/bookings/timeEstimate/TimeEstimateAddButton.tsx, src/components/bookings/timeReport/TimeReportAddButton.tsx
Seems to simply have been missed originally.
=> Bugfix: Add notifications for successfully creating time estimates and reports

src/components/TinyBookingTable.tsx, src/pages/users/[id]/index.tsx
=> Feature: Sort booking table descending

src/document-templates/index.tsx, src/pages/api/documents/invoice/[exportType]/[language]/[bookingId].ts
Change _txt_ to _pdf_ for pdf downloads.
=> Bugfix: Fix file ending of invoice data pdf download

src/components/LargeBookingTable.tsx, src/components/bookings/PreviousBookingsCard.tsx, src/pages/bookings/[id]/index.tsx
* Limit list size
* Modal to show all
* Show status and other data in modal using LargeBookingTable
---
Previous bookings for customer now follows the same format as recent changes, i.e. first 3 are shown and a link to a modal with all is provided.
---
=> Feature: Improve other booking for customer display

src/components/bookings/equipmentLists/EquipmentListTable.tsx, src/components/bookings/timeEstimate/TimeEstimateAddButton.tsx, src/components/bookings/timeEstimate/TimeEstimateList.tsx, src/components/bookings/timeReport/TimeReportList.tsx, src/document-templates/defaultTextResources.ts, src/lib/changelogUtils.ts, src/lib/db-access/equipmentList.ts, src/pages/api/sendMessage/toBookingOwners.ts
They look different today:
Not anymore! :)
=> Feature: Unify looks of time report and estimate buttons

src/components/invoices/ViewInvoiceGroupModal.tsx, src/lib/datetimeUtils.ts
Add button to auto-magically enter all invoice references.
---
Resolves #90
=> Feature: Add UX to set multiple invoice numbers at once

src/components/LargeBookingTable.tsx, src/components/bookings/BookingForm.tsx, src/components/bookings/timeReport/TimeReportModal.tsx, src/lib/utils.ts
=> Feature: Sort users alphabetically in dropdowns

src/components/LargeBookingTable.tsx, src/components/LargeEquipmentPackageTable.tsx, src/components/LargeEquipmentTable.tsx, src/lib/utils.ts
Add filter to booking lists for:
*  Customer name
* Location
* Booking type
* Price plan
* Account kind
Resolves #87
=> Feature: More booking filters

README.md, knex/seeds/mock.js, package.json, src/components/DoorAndKeytatus.tsx, src/pages/api/auth/mqtt-credentials.ts, src/pages/index.tsx, yarn.lock
Visar nyckel- och dörrstatus
Ansluter med mqtt för att få fram informationen. 
För att kunna testa lokalt behövs variabler enligt readmefilen.
Dessa kan hittas i bitwarden, HiveMq Stage mqtt
=> Feature: Add Mqtt status display

src/document-templates/components/invoiceInfo.tsx
Fix incorrect customer name in invoice document
=> Bugfix: Fix customer name in invoice document

src/pages/api/health.ts
Add a simple health check which responds with `{"status":"UP"}` at `/api/health`
=> Feature: Add health check

src/pages/api/files/index.ts
Hide drive items which are in the trash
=> Bugfix: Hide deleted drive items
